# fly.toml - configuration Fly.io pour Spring Boot

app = "gestion-taches-depenses" # change si tu veux un autre nom

kill_signal = "SIGINT"
kill_timeout = 5

# Dockerfile personnalis√©
[build]
  image = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80   # Fly.io mappe automatiquement 80/443 vers ton PORT interne

  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "5s"
